#!/bin/bash
wget -O events.xlsx "https://www.gencon.com/downloads/events.xlsx"
git diff events.xlsx | grep .
EXIT=$?
if [ ${EXIT} -ne 0 ]; then
  in2csv events.xlsx | csvjson > events.json
  cat events.json | jq . > events.json-clean
fi
